### ISSUE TITLE
大神 很想用你的框架，但是搜索设备的时候提示错误

### ISSUE THREAD

**Issue by ganjmeng** [yuhanle/WEBlueToothManager#1]
大神 很想用你的框架，但是搜索设备的时候提示错误，这个怎么解决啊，急！！！
![image](https://cloud.githubusercontent.com/assets/12026835/19304916/21369256-90a1-11e6-9fd7-8e709031f72b.png)

**Comment by yuhanle** [comment]
这个是你没有设置restore identifier，但是却使用了后台重连的功能。

有两种方法可以解决这个警告:
如果你使用后台重连机制，就需要设置一个标识符:

myCentralManager = [[CBCentralManager alloc] initWithDelegate:self queue:nil options:@{ CBCentralManagerOptionRestoreIdentifierKey: @"myCentralManagerIdentifier" }];

如果不需要使用这个功能就移除掉这个字典中的键值对。
